/**
 * import/writers/upsertGiftCards.js
 *
 * Creates / updates / deactivates gift cards from validated rows.
 * Per row: command DELETE → giftCardDeactivate; a gift_card_id (or UPDATE)
 * → giftCardUpdate (note + expiry); otherwise → giftCardCreate. A customer
 * email, when given on create, attaches the card to that customer.
 * Requires write_gift_cards. Codes are generated by Shopify — the created
 * card's masked code is surfaced in the row comment.
 */

const CREATE = `#graphql
  mutation CreateGiftCard($input: GiftCardCreateInput!) {
    giftCardCreate(input: $input) {
      giftCard { id maskedCode }
      userErrors { field message }
    }
  }
`;
const UPDATE = `#graphql
  mutation UpdateGiftCard($id: ID!, $input: GiftCardUpdateInput!) {
    giftCardUpdate(id: $id, input: $input) {
      giftCard { id }
      userErrors { field message }
    }
  }
`;
const DEACTIVATE = `#graphql
  mutation DeactivateGiftCard($id: ID!) {
    giftCardDeactivate(id: $id) {
      giftCard { id }
      userErrors { field message }
    }
  }
`;
const CUSTOMER_BY_EMAIL = `#graphql
  query CustomerByEmail($query: String!) {
    customers(first: 1, query: $query) { nodes { id } }
  }
`;

export async function upsertGiftCards(rows, admin, { onProgress } = {}) {
  const result = { created: 0, updated: 0, deleted: 0, skipped: 0, errors: [], results: new Array(rows.length) };

  let base = 0;
  for (const batch of chunk(rows, 16)) {
    const start = base;
    await Promise.all(batch.map((row, k) =>
      writeRow(row, admin, result).then((o) => { result.results[start + k] = o; onProgress?.(1); })
    ));
    base += batch.length;
    await sleep(20);
  }
  return result;
}

async function writeRow(row, admin, result) {
  const gid = row.gift_card_id ? `gid://shopify/GiftCard/${row.gift_card_id}` : null;
  const label = row.gift_card_id || row.customer_email || "(gift card)";
  try {
    if (row.command === "DELETE") {
      if (!gid) { result.skipped++; return { status: "skipped", comment: "No matching gift card to deactivate" }; }
      const { userErrors } = await run(admin, DEACTIVATE, { id: gid }, "giftCardDeactivate");
      if (userErrors.length) { result.errors.push({ path: label, userErrors }); return { status: "failed", comment: msgs(userErrors) }; }
      result.deleted++;
      return { status: "deleted", comment: "Deactivated" };
    }

    if (gid) {
      const input = {};
      if (row.note) input.note = row.note;
      if (row.expires_on) input.expiresOn = row.expires_on;
      if (!Object.keys(input).length) { result.skipped++; return { status: "skipped", comment: "Nothing to update (only note/expires_on are editable)" }; }
      const { userErrors } = await run(admin, UPDATE, { id: gid, input }, "giftCardUpdate");
      if (userErrors.length) { result.errors.push({ path: label, userErrors }); return { status: "failed", comment: msgs(userErrors) }; }
      result.updated++;
      return { status: "updated", comment: "" };
    }

    const input = { initialValue: row.initial_value };
    if (row.note) input.note = row.note;
    if (row.expires_on) input.expiresOn = row.expires_on;
    if (row.customer_email) {
      const customerId = await findCustomer(admin, row.customer_email);
      if (customerId) input.customerId = customerId;
    }
    const { userErrors, node } = await run(admin, CREATE, { input }, "giftCardCreate");
    if (userErrors.length) { result.errors.push({ path: label, userErrors }); return { status: "failed", comment: msgs(userErrors) }; }
    result.created++;
    return { status: "created", comment: node?.maskedCode ? `Code ${node.maskedCode}` : "" };
  } catch (err) {
    result.errors.push({ path: label, message: err.message });
    return { status: "failed", comment: err.message };
  }
}

async function findCustomer(admin, email) {
  const res = await admin.graphql(CUSTOMER_BY_EMAIL, { variables: { query: `email:${JSON.stringify(email)}` } });
  const { data } = await res.json();
  return data?.customers?.nodes?.[0]?.id ?? null;
}

/** Join userError messages into one comment string. */
function msgs(errs) {
  return errs.map((e) => e.message).filter(Boolean).join("; ");
}

// ─── helpers ────────────────────────────────────────────────────────────────

async function run(admin, mutation, variables, field) {
  const res = await admin.graphql(mutation, { variables });
  const { data } = await res.json();
  return { userErrors: data?.[field]?.userErrors ?? [], node: data?.[field]?.giftCard ?? null };
}

function chunk(arr, size) {
  const result = [];
  for (let i = 0; i < arr.length; i += size) result.push(arr.slice(i, i + size));
  return result;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
